In [6]:
import numpy as np
from tensorflow import keras

## Conv1D

In [12]:
# define input data
data = np.asarray([0, 0, 0, 1, 1, 0, 0, 0])
data = data.reshape(1, 8, 1)
# n_sample x sample_len x n_features
data

array([[[0],
        [0],
        [0],
        [1],
        [1],
        [0],
        [0],
        [0]]])

In [13]:
# create model
model = keras.models.Sequential()
model.add(keras.layers.Conv1D(filters=1, kernel_size=3, input_shape=(8, 1)))

- filters: Integer, the dimensionality of the output space (i.e. the number of output filters in the convolution). (could be 64, lol)
- kernel_size: An integer or tuple/list of a single integer, specifying the length of the 1D convolution window. (here one feature on a time axis vertical applied 1D Filter)

### Kernel
The weights must be specified in a three-dimensional structure, in terms of rows, columns, and channels. The filter has a single row, three columns, and one channel.
- same structure as input data

In [14]:
model.get_weights()

[array([[[-0.10491657]],
 
        [[-0.5013337 ]],
 
        [[ 0.01941633]]], dtype=float32),
 array([0.], dtype=float32)]

In [15]:
# define a vertical line detector
# its a [0, 1, 0] kernel!
weights = [np.asarray([[[0]],[[1]],[[0]]]), np.asarray([0.0])]
# store the weights in the model
model.set_weights(weights)
model.get_weights()

[array([[[0.]],
 
        [[1.]],
 
        [[0.]]], dtype=float32),
 array([0.], dtype=float32)]

### Apply

In [17]:
# apply filter to input data
yhat = model.predict(data)
yhat

array([[[0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.]]], dtype=float32)

this is the result of going one step at a time 
- always multiplying
```
[0, 0, 0, 1, 1, 0, 0, 0]
[0, 1, 0] = 0
   [0, 1, 0] = 0
      [0, 1, 0] = 1
````
 

In [20]:
np.asarray([0, 1, 0]).dot(np.asarray([0, 1, 1]))

1

# Conv2D

In [24]:
# define input data
data = [[0, 0, 0, 1, 1, 0, 0, 0],
		[0, 0, 0, 1, 1, 0, 0, 0],
		[0, 0, 0, 1, 1, 0, 0, 0],
		[0, 0, 0, 1, 1, 0, 0, 0],
		[0, 0, 0, 1, 1, 0, 0, 0],
		[0, 0, 0, 1, 1, 0, 0, 0],
		[0, 0, 0, 1, 1, 0, 0, 0],
		[0, 0, 0, 1, 1, 0, 0, 0]]
data = np.asarray(data)
data = data.reshape(1, 8, 8, 1)

# create model
model = keras.models.Sequential()
model.add(keras.layers.Conv2D(filters=1, kernel_size=(3,3), input_shape=(8, 8, 1)))

# define a vertical line detector
detector = [[[[0]],[[1]],[[0]]],
            [[[0]],[[1]],[[0]]],
            [[[0]],[[1]],[[0]]]]
weights = [np.asarray(detector), np.asarray([0.0])]
# for every any application of the filter we will add the bias!

# store the weights in the model
model.set_weights(weights)
# confirm they were stored
print(model.get_weights())

[array([[[[0.]],

        [[1.]],

        [[0.]]],


       [[[0.]],

        [[1.]],

        [[0.]]],


       [[[0.]],

        [[1.]],

        [[0.]]]], dtype=float32), array([0.], dtype=float32)]


In [25]:
# apply filter to input data
yhat = model.predict(data)
yhat

array([[[[0.],
         [0.],
         [3.],
         [3.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [3.],
         [3.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [3.],
         [3.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [3.],
         [3.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [3.],
         [3.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [3.],
         [3.],
         [0.],
         [0.]]]], dtype=float32)

In [26]:
for r in range(yhat.shape[1]):
	# print each column in the row
	print([yhat[0,r,c,0] for c in range(yhat.shape[2])])

[0.0, 0.0, 3.0, 3.0, 0.0, 0.0]
[0.0, 0.0, 3.0, 3.0, 0.0, 0.0]
[0.0, 0.0, 3.0, 3.0, 0.0, 0.0]
[0.0, 0.0, 3.0, 3.0, 0.0, 0.0]
[0.0, 0.0, 3.0, 3.0, 0.0, 0.0]
[0.0, 0.0, 3.0, 3.0, 0.0, 0.0]
